services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - mynetwork

  fastapi:
    build: .  # Build the FastAPI app from the local Dockerfile
    container_name: fastapi
    ports:
      - "9567:9567"
    depends_on:
      - elasticsearch
    networks:
      - mynetwork

volumes:
  esdata:
    driver: local

networks:
  mynetwork:
    driver: bridge